<!-- JavaScript tryâ€¦catch -->
<!-- it is used to handle the error-prone part of the code
It initially tests the code for all possible errors it may contain, then it implements actions to tackle those errors (if occur).

try{} statement: Here, the code which needs possible error testing is kept within the try block.
catch{} statement: This block handles the error of the code by executing the set of statements written within the block.

Note: catch {} statement executes only after the execution of the try {} statement. Also, one try block can contain one or more catch blocks --> 


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exception Handling</title>
</head>
<body>
     
<script>  
    try{  
    var a= ["34","32","5","31","24","44","67"]; //a is an array  
    document.write(a);    // displays elements of a  
    document.write(b); //b is undefined but still trying to fetch its value. Thus catch block will be invoked  
    }catch(e){  
    alert("There is error which shows "+e.message); //Handling error  
    }  
    </script>
</body>
</html>
